name: Build and Push Multi-Arch Docker Image

on:
  push:
    branches:
      - master
  workflow_dispatch:  # ✅ 启用手动运行按钮

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        no-cache: true            # ✅ 禁用缓存，强制重新构建
        tags: aoxijy/sub-web:latest
